version: "3.8"

services:
  # 后端服务
  backend:
    build:
      context: ./meeting_room_booking_system_backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3005:3005"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # 前端管理界面服务
  frontend-admin:
    build:
      context: ./meeting_room_booking_system_frontend_admin
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:80"
    networks:
      - app-network

  # 前端用户界面服务
  frontend-user:
    build:
      context: ./meeting_room_booking_system_frontend_user
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
