version: '3.8'
services:
  fe-admin-app:
    build:
      context: ../meeting_room_booking_system_frontend_admin
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - nest-app
    restart: always
    networks:
      - common-network
  fe-user-app:
    build:
      context: ../meeting_room_booking_system_frontend_user
      dockerfile: ./Dockerfile
    ports:
      - 81:80
    depends_on:
      - nest-app
    restart: always
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3005:3005
    depends_on:
      - mysql-container
      - redis-container
    restart: always
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/lqt/mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: lqt
    restart: always
    ports:
      - 3306:3306
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/lqt/redis-data:/data
    restart: always
    ports:
      - 6379:6379
    networks:
      - common-network
  minio-container:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /Users/lqt/minio:/data
    environment:
      MINIO_ROOT_USER: lqt
      MINIO_ROOT_PASSWORD: lqt123456
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
