version: '3.8'

services:
  meeting-room-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting-room-backend
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      # 数据库配置 - 连接到外部数据库
      - mysql_host=${MYSQL_HOST:-localhost}
      - mysql_port=${MYSQL_PORT:-3306}
      - mysql_user=${MYSQL_USER:-root}
      - mysql_password=${MYSQL_PASSWORD}
      - mysql_database=${MYSQL_DATABASE:-meeting_room_booking_system}
      - mysql_logging=${MYSQL_LOGGING:-true}
      - mysql_pool_size=${MYSQL_POOL_SIZE:-10}
      - mysql_synchronize=${MYSQL_SYNCHRONIZE:-true}
      - mysql_connect_timeout=${MYSQL_CONNECT_TIMEOUT:-60000}
      - mysql_acquire_timeout=${MYSQL_ACQUIRE_TIMEOUT:-60000}
      - mysql_idle_timeout=${MYSQL_IDLE_TIMEOUT:-300000}
      
      # Redis配置 - 连接到外部Redis
      - redis_server_host=${REDIS_HOST:-localhost}
      - redis_server_port=${REDIS_PORT:-6379}
      - redis_server_password=${REDIS_PASSWORD}
      - redis_server_db=${REDIS_DB:-0}
      
      # JWT配置
      - jwt_secret=${JWT_SECRET}
      - jwt_access_token_expires_time=${JWT_ACCESS_TOKEN_EXPIRES:-30m}
      - jwt_refresh_token_expires_time=${JWT_REFRESH_TOKEN_EXPIRES:-7d}
      
      # 邮件配置
      - email_host=${EMAIL_HOST:-smtp.qq.com}
      - email_port=${EMAIL_PORT:-587}
      - email_secure=${EMAIL_SECURE:-false}
      - email_user=${EMAIL_USER}
      - email_pass=${EMAIL_PASSWORD}
      - email_from=${EMAIL_FROM}
      - email_from_name=${EMAIL_FROM_NAME:-会议房间预订系统}
      
      # Nest配置
      - nest_port=${NEST_PORT:-3005}
    networks:
      - meeting-room-network
    depends_on:
      - wait-for-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 等待数据库和Redis启动的辅助服务
  wait-for-db:
    image: alpine:latest
    container_name: wait-for-services
    command: |
      sh -c "
        echo '等待外部服务连接...'
        while ! nc -z ${MYSQL_HOST:-localhost} ${MYSQL_PORT:-3306}; do
          echo '等待MySQL...'
          sleep 2
        done
        echo 'MySQL已就绪'
        
        while ! nc -z ${REDIS_HOST:-localhost} ${REDIS_PORT:-6379}; do
          echo '等待Redis...'
          sleep 2
        done
        echo 'Redis已就绪'
        
        echo '所有外部服务已就绪'
        exit 0
      "
    networks:
      - meeting-room-network

networks:
  meeting-room-network:
    driver: bridge

volumes:
  meeting-room-data: